(() => {
  const DB = "resurgo-fitness-v1", STORE = "state", TODAY = new Date().toISOString().slice(0, 10);
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)], el = id => document.getElementById(id);
  const uid = p => `${p}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
  const clone = v => typeof structuredClone === "function" ? structuredClone(v) : JSON.parse(JSON.stringify(v));
  const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[c]));
  const n = id => { const v = Number(el(id)?.value); return Number.isFinite(v) ? v : 0; };
  const text = id => el(id)?.value?.trim() || "";
  const sec = s => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;
  const levels = { running:["R0","R1","R2","R3","R4"], push:["P0","P1","P2","P3","P4"], pull:["T0","T1","T2","T3","T4"], legs:["J0","J1","J2","J3","J4"], frontCore:["G0","G1","G2","G3","G4"], sideCore:["L0","L1","L2","L3","L4"], mobility:["M0","M1","M2","M3","M4"] };
  const videos = {
    defaultBase: "https://musclewiki.com",
    note: "Les vidéos sont online seulement. Certains sites peuvent refuser l'iframe ; le schéma animé et la fiche restent disponibles offline."
  };
  const ex = [
    E("warmup_flow","Echauffement mobilité","warmup","time",1,300,0,"Mobilité douce complète.",["Respire par le nez.","Mobilise chevilles, hanches, épaules.","Garde une amplitude confortable."],"Pas de mouvement brutal.","/"),
    E("dead_bug","Dead bug","core","reps",3,8,40,"Gainage profond au sol.",["Allonge-toi sur le dos, genoux à 90 degrés.","Rentre légèrement les côtes.","Descends bras et jambe opposés sans cambrer.","Reviens lentement et alterne."],"Stop si douleur lombaire vive.","/bodyweight/male/abs/dead-bug"),
    E("bird_dog","Bird-dog","core","reps",3,8,40,"Stabilité lombaire à quatre pattes.",["Mains sous épaules, genoux sous hanches.","Tends bras et jambe opposés.","Garde le bassin face au sol.","Marque une pause puis reviens."],"Stop si douleur qui descend dans la jambe.","/bodyweight/male/lowerback/bird-dog"),
    E("front_plank","Planche avant-bras","core","time",3,25,45,"Gainage frontal sans aller à l'échec.",["Coudes sous épaules.","Fesses ni hautes ni basses.","Respire lentement.","Arrête avant de perdre la forme."],"Stop si cambrure ou douleur lombaire.","/bodyweight/male/abs/plank"),
    E("side_plank_knees","Gainage latéral genoux","core","time",2,25,35,"Stabilité latérale progressive.",["Coude sous épaule.","Genoux fléchis, hanches alignées.","Pousse le sol avec l'avant-bras.","Change de côté à chaque série."],"Stop si douleur épaule ou hanche.","/bodyweight/male/abs/side-plank"),
    E("hollow_hold","Hollow hold facile","core","time",2,20,45,"Contrôle abdominal avancé mais modulable.",["Plaque les lombaires au sol.","Garde les genoux fléchis au début.","Monte les bras seulement si le dos reste stable."],"Ne force pas si le dos se cambre.","/bodyweight/male/abs/hollow-hold"),
    E("wall_pushup","Pompes murales","push","reps",2,12,45,"Reprise très facile du mouvement de poussée.",["Mains au mur à hauteur poitrine.","Corps gainé.","Descends lentement.","Repousse sans verrouiller brutalement."],"Stop si douleur épaule.","/bodyweight/male/chest/wall-push-up"),
    E("incline_pushup","Pompes inclinées","push","reps",3,10,60,"Pompes mains sur support haut.",["Mains sur table solide ou plan de travail.","Corps en bloc.","Coudes contrôlés à 30-45 degrés.","Plus le support est bas, plus c'est dur."],"Support stable obligatoire.","/bodyweight/male/chest/incline-push-up"),
    E("knee_pushup","Pompes genoux","push","reps",3,8,60,"Progression vers les pompes complètes.",["Genoux au sol, bassin gainé.","Descends poitrine vers le sol.","Garde la nuque neutre.","Remonte sans casser les hanches."],"Stop si épaule douloureuse.","/bodyweight/male/chest/knee-push-up"),
    E("pike_pushup","Pike push-up","push","reps",2,6,75,"Poussée épaules progressive.",["Hanches hautes.","Tête descend vers le sol.","Coudes contrôlés.","Amplitude partielle au début."],"Pas de douleur cervicale ou épaule.","/bodyweight/male/shoulders/pike-push-up"),
    E("band_row","Rowing élastique","pull","reps",3,12,50,"Tirage horizontal posture.",["Ancre l'élastique solidement.","Épaules basses.","Tire les coudes vers l'arrière.","Reviens lentement."],"Vérifie l'ancrage avant chaque série.","/"),
    E("band_pulldown","Tirage vertical élastique","pull","reps",3,12,60,"Grand dorsal sans machine.",["Ancre haut.","Tire les coudes vers les côtes.","Ne hausse pas les épaules.","Contrôle le retour."],"Ancrage haut très solide.","/"),
    E("reverse_fly","Oiseau élastique","pull","reps",2,12,50,"Arrière d'épaule et posture.",["Bras presque tendus.","Ouvre doucement.","Serre les omoplates sans cambrer.","Retour lent."],"Charge très légère.","/"),
    E("sit_to_stand","Assis-debout","legs","reps",3,12,60,"Base jambes et genoux.",["Pieds largeur bassin.","Pousse le sol.","Genoux alignés avec les pieds.","Assieds-toi lentement."],"Stop si douleur genou forte.","/bodyweight/male/quads/bodyweight-squat"),
    E("box_squat","Squat sur chaise","legs","reps",3,10,60,"Squat sécurisé avec repère.",["Hanches vers l'arrière.","Touche la chaise sans t'écraser.","Remonte en poussant les pieds.","Garde le buste long."],"Réduis amplitude si genou sensible.","/bodyweight/male/quads/squat"),
    E("split_squat","Fente statique assistée","legs","reps",2,8,70,"Force unilatérale progressive.",["Tiens un support.","Descends verticalement.","Genou avant aligné.","Petite amplitude au départ."],"Stop si tendon ou genou augmente.","/bodyweight/male/quads/split-squat"),
    E("glute_bridge","Pont fessier","legs","reps",3,12,45,"Fessiers et protection lombaire.",["Dos au sol, pieds proches.","Pousse les talons.","Monte sans cambrer.","Redescends lentement."],"Pas de pincement lombaire.","/bodyweight/male/glutes/glute-bridge"),
    E("calf_raise","Montées mollets","legs","reps",3,15,45,"Mollets et tendon d'Achille.",["Tiens un support.","Monte sur pointes.","Pause en haut.","Descends lentement."],"Stop si tendon douloureux.","/bodyweight/male/calves/calf-raise"),
    E("hip_hinge","Charnière hanche","legs","reps",3,10,45,"Apprendre à plier aux hanches.",["Mains sur hanches.","Fesses vers l'arrière.","Dos long.","Genoux légèrement fléchis."],"Pas de dos rond sous fatigue.","/"),
    E("hip_flexor","Mobilité psoas","mobility","time",2,35,20,"Ouverture de hanche.",["Position fente basse.","Rentre légèrement le bassin.","Respire lentement.","Change de côté."],"Ne force jamais.","/bodyweight/male/stretching/hip-flexor-stretch"),
    E("thoracic_rotation","Rotation thoracique","mobility","reps",2,8,20,"Mobilité haut du dos.",["À quatre pattes.","Main derrière la tête.","Tourne sans bouger le bassin.","Regarde le coude."],"Pas de douleur vive.","/"),
    E("ankle_wall","Cheville genou au mur","mobility","reps",2,8,20,"Mobilité cheville.",["Talon au sol.","Genou vers le mur.","Cherche une tension douce.","Change de côté."],"Pas de douleur tendon.","/"),
    E("hamstring_floss","Floss ischios","mobility","reps",2,10,20,"Souplesse arrière de jambe.",["Allonge la jambe sans verrouiller.","Pointe puis flex pied.","Amplitude confortable.","Respire."],"Pas de tiraillement nerveux fort.","/"),
    E("shoulder_wall_slide","Wall slide épaules","mobility","reps",2,10,30,"Mobilité épaules et posture.",["Dos au mur si possible.","Monte les bras lentement.","Garde côtes basses.","Redescends contrôlé."],"Stop si pincement épaule.","/"),
    E("brisk_walk","Marche active","cardio","time",1,1800,0,"Cardio bas impact.",["Rythme soutenu.","Tu dois pouvoir parler.","Bras actifs.","Ralentis si douleur."],"Ralentis si douleur augmente.","/"),
    E("easy_run","Course facile","cardio","time",1,1800,0,"Footing en aisance respiratoire.",["Départ très lent.","Tu dois pouvoir parler.","Foulée courte.","Stop si tendon ou douleur irradiée."],"Pas de fractionné en reprise.","/"),
    E("run_walk","Alternance course-marche","cardio","time",1,1500,0,"Retour course progressif.",["Alterner 1-3 min course et marche.","Reste facile.","Note douleur et souffle.","Augmente seulement si tout va bien."],"Pas deux courses si douleur ou poids/fatigue défavorables.","/"),
    E("low_impact_cardio","Cardio bas impact","cardio","time",1,1500,0,"Vélo, rameur doux ou marche inclinée.",["Zone facile.","Cadence régulière.","Respiration contrôlée.","Reste frais en fin."],"Stop si douleur augmente.","/"),
    E("step_up_low","Step-up bas","legs","reps",2,10,60,"Montée sur marche basse.",["Marche basse et stable.","Pousse dans le talon.","Redescends lentement.","Change de jambe."],"Pas de douleur genou.","/bodyweight/male/quads/step-up"),
    E("cooldown_breathing","Retour au calme respiration","cooldown","time",1,180,0,"Retour au calme.",["Allonge l'expiration.","Relâche épaules.","Observe douleur et fatigue.","Note le ressenti."],"Reste confortable.","/")
  ];
  const empty = {
    schemaVersion:"1.1.0-vanilla", activeProfileId:null, profiles:[], assessments:[], plans:[], sessionRuns:[], metrics:[], activities:[],
    sources:[{id:"manual",label:"Manuel",enabled:true,priority:3},{id:"json_import",label:"Import JSON",enabled:true,priority:2},{id:"mock_garmin",label:"Mock Garmin",enabled:true,priority:1},{id:"worker",label:"Worker Cloudflare",enabled:false,priority:1}],
    settings:{ tts:{enabled:true,rate:1,pitch:1,volume:1,countdown:true,rest:true,cues:true,safetyAlways:true}, workerUrl:"", workerToken:"", videoBase:videos.defaultBase },
    ui:{ view:"today", search:"", filter:"all", message:"" }
  };
  let state = clone(empty), tick = null, left = 0;

  function E(id,name,family,type,sets,amount,rest,short,steps,safety,path) {
    return { id,name,family,type,sets,rest,short,steps,safety,cue:steps[0], reps:type==="reps"?amount:null, seconds:type==="time"?amount:null, videoPath:path };
  }
  function db(){ return new Promise((ok,ko)=>{ const r=indexedDB.open(DB,1); r.onupgradeneeded=()=>r.result.createObjectStore(STORE); r.onsuccess=()=>ok(r.result); r.onerror=()=>ko(r.error); }); }
  async function get(k){ const d=await db(); return new Promise((ok,ko)=>{ const r=d.transaction(STORE).objectStore(STORE).get(k); r.onsuccess=()=>ok(r.result); r.onerror=()=>ko(r.error); }); }
  async function put(k,v){ const d=await db(); return new Promise((ok,ko)=>{ const r=d.transaction(STORE,"readwrite").objectStore(STORE).put(v,k); r.onsuccess=ok; r.onerror=()=>ko(r.error); }); }
  async function save(msg=""){ if(msg) state.ui.message=msg; await put("app",state); }
  const profile=()=>state.profiles.find(p=>p.id===state.activeProfileId);
  const plan=()=>profile()?state.plans.filter(s=>s.profileId===profile().id&&!s.completedAt):[];
  const run=()=>state.sessionRuns.find(r=>!r.completedAt&&!r.abortedAt);
  const exercise=id=>ex.find(x=>x.id===id)||ex[0];
  const currentEx=()=>{ const r=run(), s=state.plans.find(x=>x.id===r?.sessionId); return exercise(s?.exerciseIds[r.exerciseIndex]); };
  const latestMetric=()=>{ const p=profile(); const a=p?state.metrics.filter(m=>m.profileId===p.id&&m.weightKg).sort((a,b)=>new Date(a.measuredAt)-new Date(b.measuredAt)):[]; return a[a.length-1]||null; };

  function createProfile(){
    const name = text("newProfileName") || `Profil ${state.profiles.length + 1}`;
    const p={ id:uid("profile"), name, createdAt:new Date().toISOString(), age:n("newAge")||null, heightCm:n("newHeight")||null, startWeightKg:n("newWeight")||null, targetWeightKg:n("newTarget")||null, availabilityDays:3, equipment:"élastique, chaise, tapis", sportsHistory:"", health:{backPain:0,kneePain:0,tendonPain:0,fatigue:1,irradiating:false,neurological:false}, levels:{running:"R1",push:"P1",pull:"T1",legs:"J1",frontCore:"G1",sideCore:"L1",mobility:"M1"}, dataPreferences:{primaryWeight:"garmin_index_s2",primaryActivities:"garmin",dedup:true} };
    state.profiles.push(p); state.activeProfileId=p.id; state.assessments.push({id:uid("assessment"),profileId:p.id,date:TODAY,tests:clone(p.levels)}); makeWeek(p.id); save("Profil créé.").then(render);
  }
  function makeWeek(pid,short=false){
    const p=state.profiles.find(x=>x.id===pid); if(!p) return;
    const protect=p.health.backPain>=3||p.health.kneePain>=3||p.health.tendonPain>=3||p.health.irradiating||p.health.neurological;
    const cardio=protect?"brisk_walk":(p.levels.running==="R0"?"run_walk":"easy_run");
    const A=short?["warmup_flow","dead_bug","bird_dog","sit_to_stand","cooldown_breathing"]:["warmup_flow","dead_bug","bird_dog","incline_pushup","band_row","sit_to_stand","glute_bridge","cooldown_breathing"];
    const B=short?["hip_flexor","thoracic_rotation","bird_dog"]:["hip_flexor","ankle_wall","side_plank_knees","band_pulldown","box_squat","calf_raise"];
    const C=short?["warmup_flow","low_impact_cardio","cooldown_breathing"]:["warmup_flow",cardio,"cooldown_breathing"];
    const sets=[["Force profonde",short?22:42,"strength",A], [protect?"Cardio protection":"Endurance facile",protect?25:35,"cardio",C], ["Renfo mobilité",short?18:34,"mobility",B]];
    state.plans=state.plans.filter(s=>!(s.profileId===pid&&!s.completedAt));
    state.plans.push(...sets.map((s,i)=>({id:uid(`session${i}`),profileId:pid,title:s[0],minutes:s[1],type:s[2],phase:1,week:1,date:TODAY,exerciseIds:s[3],short,completedAt:null})));
  }
  function decision(p){
    const planned=state.plans.filter(s=>s.profileId===p.id), done=planned.filter(s=>s.completedAt).length, adh=planned.length?done/planned.length:0, pain=Math.max(p.health.backPain,p.health.kneePain,p.health.tendonPain);
    if(p.health.irradiating||p.health.neurological||pain>=3||p.health.fatigue>=5) return ["red","Protection","Douleur/fatigue élevée : mobilité, marche, gainage profond, aucune progression."];
    if(adh<.4||p.health.fatigue>=4) return ["orange","Correction","Semaine minimale viable et reprise du rythme."];
    if(adh>=.65&&pain<=2&&p.health.fatigue<=3) return ["green","Progression","Augmentation légère possible la semaine suivante."];
    return ["blue","Maintien","Répéter proprement sans chercher la performance."];
  }
  function start(id){ const s=state.plans.find(x=>x.id===id); if(!s) return; state.sessionRuns=state.sessionRuns.filter(x=>x.completedAt||x.abortedAt); state.sessionRuns.push({id:uid("run"),profileId:s.profileId,sessionId:s.id,exerciseIndex:0,setIndex:0,mode:"work",logs:[],safetyAlerts:[],startedAt:new Date().toISOString(),completedAt:null,abortedAt:null}); state.ui.view="session"; speak(`Prochain exercice. ${currentEx().name}. ${currentEx().cue}`); save("Séance lancée.").then(render); }
  function log(success,pain,difficulty){
    stopTimer(); const r=run(), s=state.plans.find(x=>x.id===r?.sessionId), x=currentEx(); if(!r||!s||!x) return;
    r.logs.push({exerciseId:x.id,set:r.setIndex+1,success,pain,difficulty,at:new Date().toISOString()});
    if(pain>=3){r.safetyAlerts.push(`${x.name}: douleur ${pain}/5`); speak("Alerte sécurité. Stop ou version plus facile.","safety");}
    const doneEx=pain>=3||success==="stop"||r.setIndex+1>=x.sets;
    if(doneEx&&r.exerciseIndex+1>=s.exerciseIds.length){r.completedAt=s.completedAt=new Date().toISOString(); r.mode="done"; state.activities.push({id:uid("activity"),profileId:r.profileId,source:"manual",type:s.type,startedAt:r.startedAt,durationSeconds:s.minutes*60,sessionRunId:r.id}); state.ui.view="stats"; speak("Séance terminée. Résumé enregistré.");}
    else if(doneEx){r.mode="resting"; r.restNext={exerciseIndex:r.exerciseIndex+1,setIndex:0,label:`Exercice suivant : ${exercise(s.exerciseIds[r.exerciseIndex+1]).name}`}; startRest(x.rest||30);}
    else {r.mode="resting"; r.restNext={exerciseIndex:r.exerciseIndex,setIndex:r.setIndex+1,label:`Série suivante : ${r.setIndex+2} sur ${x.sets}`}; startRest(x.rest||30);}
    save("Résultat enregistré.").then(render);
  }
  function speak(t,kind="cue"){ if((!state.settings.tts.enabled&&kind!=="safety")||!("speechSynthesis" in window)) return; if(kind==="safety") speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(t); u.lang="fr-FR"; u.rate=state.settings.tts.rate; u.pitch=state.settings.tts.pitch; u.volume=state.settings.tts.volume; speechSynthesis.speak(u); }
  function startTimer(){ const x=currentEx(); if(!x) return; stopTimer(); left=x.type==="time"?x.seconds:5; updateTimer(); speak(x.type==="time"?"Timer lancé.":"Prévisualisation."); tick=setInterval(()=>{ left--; if(state.settings.tts.countdown&&[10,5,3,2,1].includes(left)) speak(String(left),"timer"); updateTimer(); if(left<=0){stopTimer(); speak("Temps terminé. Enregistre le résultat.");}},1000); }
  function startRest(seconds){ stopTimer(); left=seconds; if(state.settings.tts.rest) speak(`Repos ${seconds} secondes. La prochaine série ne démarre pas automatiquement.`,"timer"); tick=setInterval(()=>{ left--; if(state.settings.tts.countdown&&[30,20,10,5,3,2,1].includes(left)) speak(left===30||left===20||left===10?`${left} secondes` : String(left),"timer"); updateTimer(); if(left<=0){stopTimer(); speak("Repos terminé. Appuie sur commencer quand tu es prêt.","timer"); render();}},1000); }
  function continueAfterRest(){ const r=run(); if(!r?.restNext) return; r.exerciseIndex=r.restNext.exerciseIndex; r.setIndex=r.restNext.setIndex; r.mode="work"; r.restNext=null; left=0; speak(`Prêt. ${currentEx().name}. ${currentEx().cue}`); save("Série suivante prête.").then(render); }
  function stopTimer(){ if(tick) clearInterval(tick); tick=null; }
  function updateTimer(){ const t=el("timer"); if(t) t.textContent=sec(Math.max(left,0)); }

  function shell(content){ const nav=["today","plan","session","exercises","stats","settings"]; const names={today:"Aujourd'hui",plan:"Plan",session:"Séance",exercises:"Exos",stats:"Stats",settings:"Réglages"}, icons={today:"⌂",plan:"▦",session:"▶",exercises:"◉",stats:"◷",settings:"⚙"}; return `<main class="app"><header class="top"><div class="brand"><span class="logo">RG</span><span>ResurGo</span></div><span class="pill">${navigator.onLine?"Online":"Offline"} · PWA</span></header><nav class="tabs">${nav.map(v=>`<button class="tab ${state.ui.view===v?"active":""}" data-view="${v}"><span>${icons[v]}</span><span>${names[v]}</span></button>`).join("")}</nav><section class="content">${state.ui.message?`<p class="notice">${esc(state.ui.message)}</p>`:""}${content}</section></main>`; }
  function today(){ const p=profile(); if(!p) return `<section class="hero"><p class="eyebrow">Coach sportif local-first</p><h1>ResurGo Fitness</h1><p>PWA offline avec séances guidées, exercices détaillés, stats, saisie course/balance et Worker Garmin optionnel.</p>${newProfileBox()}</section>`; const d=decision(p), m=latestMetric(), next=plan()[0]; return `<section class="grid"><h1>Aujourd'hui</h1><div class="grid two"><article class="panel"><p class="eyebrow">Profil actif</p><h2>${esc(p.name)}</h2><div class="row"><span>Objectif</span><strong>${p.startWeightKg||"?"} → ${p.targetWeightKg||"?"} kg</strong></div><div class="row"><span>Poids récent</span><strong>${m?m.weightKg+" kg":"À saisir"}</strong></div><div class="row"><span>Décision</span><strong class="status ${d[0]}">${d[1]}</strong></div><p class="muted">${d[2]}</p></article><article class="panel"><p class="eyebrow">Séance recommandée</p><h2>${next?.title||"Plan à générer"}</h2><p class="muted">${next?`${next.minutes} min · ${next.exerciseIds.length} blocs`:"Aucune séance active."}</p><div class="actions"><button class="primary" id="startToday">Démarrer</button><button class="secondary" id="shortWeek">Semaine courte</button><button class="secondary" id="activeRest">Repos actif</button></div></article></div><article class="panel"><h2>Check rapide</h2><p class="muted">0 = aucune douleur/fatigue, tout va bien. 5 = alerte forte, on protège et on évite de progresser.</p><div class="grid three"><label>Dos 0-5<input id="quickBack" type="number" min="0" max="5" value="${p.health.backPain}"></label><label>Genou/tendon 0-5<input id="quickKnee" type="number" min="0" max="5" value="${Math.max(p.health.kneePain,p.health.tendonPain)}"></label><label>Fatigue 0-5<input id="quickFatigue" type="number" min="0" max="5" value="${p.health.fatigue}"></label></div><button class="secondary" id="saveQuick">Enregistrer check</button></article><p class="notice">Sécurité : stop en cas de douleur irradiée, faiblesse, engourdissement, douleur forte ou symptôme inquiétant.</p></section>`; }
  function planView(){ if(!profile()) return needProfile(); return `<section class="grid"><h1>Plan adaptatif</h1><div class="actions"><button class="primary" id="regen">Générer semaine</button><button class="secondary" id="shortWeek">Semaine minimale viable</button></div>${plan().map(s=>`<article class="panel"><p class="eyebrow">Phase ${s.phase} · semaine ${s.week} · ${s.type}</p><h2>${s.title}</h2><p class="muted">${s.minutes} min</p><div class="chips">${s.exerciseIds.map(id=>`<span>${exercise(id).name}</span>`).join("")}</div><button class="primary" data-start="${s.id}">Lancer</button></article>`).join("")}</section>`; }
  function sessionView(){ const r=run(); if(!r) return `<section class="grid"><h1>Séance</h1><article class="panel"><p>Aucune séance en cours.</p><button class="primary" id="startToday">Lancer la prochaine séance</button></article></section>`; const s=state.plans.find(x=>x.id===r.sessionId), x=currentEx(), logs=r.logs.filter(l=>l.exerciseId===x.id), done=logs.length, pct=Math.round(done/x.sets*100); if(r.mode==="resting") return `<section class="session rest"><article class="panel coach"><p class="eyebrow">${s.title} · récupération</p><h1>Repos</h1><div class="timer" id="timer">${sec(Math.max(left,0))}</div><p class="muted">${esc(r.restNext?.label||"Série suivante")}</p><p>Respire, bois une gorgée si besoin, vérifie douleur et technique. La suite démarre uniquement quand tu appuies sur le bouton.</p><div class="actions"><button class="primary" id="continueAfterRest">Commencer quand je suis prêt</button><button class="secondary" id="skipRest">Passer le repos</button><button class="danger" id="abortSession">Abandonner</button></div></article></section>`; return `<section class="session"><div class="media">${media(x)}</div><article class="panel coach"><p class="eyebrow">${s.title} · exercice ${r.exerciseIndex+1}/${s.exerciseIds.length}</p><h1>${x.name}</h1><div class="setbox"><strong>Série ${Math.min(done+1,x.sets)} / ${x.sets}</strong><span>${pct}% fait</span><progress max="${x.sets}" value="${done}"></progress></div><p>${x.short}</p><ol>${x.steps.map(v=>`<li>${esc(v)}</li>`).join("")}</ol><p class="notice">${x.safety}</p><div class="timer" id="timer">${x.type==="time"?sec(left||x.seconds):`${x.reps} reps`}</div><div class="actions"><button class="primary" id="startTimer">${x.type==="time"?"Lancer timer":"Prévisualiser"}</button><button class="primary" id="okSet">Série réussie</button><button class="secondary" id="partialSet">Partiel / dur</button><button class="danger" id="painSet">Douleur / stop</button><button class="secondary" id="speakCue">Voix</button><button class="danger" id="abortSession">Abandonner</button></div></article></section>`; }
  function exercisesView(){ const f=state.ui.filter, q=state.ui.search.toLowerCase(), fam=[...new Set(ex.map(x=>x.family))], list=ex.filter(x=>(f==="all"||x.family===f)&&`${x.name} ${x.family} ${x.short} ${x.steps.join(" ")}`.toLowerCase().includes(q)); return `<section class="grid"><h1>Bibliothèque</h1><div class="panel"><div class="grid three"><label>Recherche<input id="search" value="${esc(state.ui.search)}" placeholder="dos, pompe, course..."></label><label>Famille<select id="familyFilter"><option value="all">Toutes</option>${fam.map(x=>`<option value="${x}" ${f===x?"selected":""}>${x}</option>`).join("")}</select></label><p class="muted">${list.length} exercices · vidéo online, fiche et animation offline</p></div></div><div class="exerciseGrid">${list.map(card).join("")}</div></section>`; }
  function stats(){ if(!profile()) return needProfile(); const p=profile(), m=state.metrics.filter(x=>x.profileId===p.id).sort((a,b)=>new Date(a.measuredAt)-new Date(b.measuredAt)), acts=state.activities.filter(x=>x.profileId===p.id), done=state.sessionRuns.filter(x=>x.profileId===p.id&&x.completedAt), last=m[m.length-1], trend=m.length>1&&last.weightKg&&m[0].weightKg?(last.weightKg-m[0].weightKg).toFixed(1):"0.0"; return `<section class="grid"><h1>Statistiques</h1><div class="grid three"><article class="panel"><p class="eyebrow">Poids</p><h2>${last?.weightKg?last.weightKg+" kg":"À saisir"}</h2></article><article class="panel"><p class="eyebrow">Tendance poids</p><h2>${trend} kg</h2></article><article class="panel"><p class="eyebrow">Séances terminées</p><h2>${done.length}</h2></article></div><div class="grid two"><article class="panel"><h2>Poids / tour ventre</h2>${chart(m,"weightKg","waistCm")}</article><article class="panel"><h2>Activité course</h2>${bar(acts.filter(a=>a.type==="run"||a.type==="walk").slice(-10).map(a=>({label:new Date(a.startedAt).toLocaleDateString("fr-FR",{day:"2-digit",month:"2-digit"}),value:a.distanceKm||a.durationSeconds/600})))}</article></div><article class="panel"><h2>Pesée manuelle / Garmin Index S2</h2><div class="grid four">${["weightKg:Poids kg","bodyFatPct:% graisse","waterPct:% eau","bmi:IMC","boneKg:Masse os kg","muscleKg:Masse muscle kg","waistCm:Tour ventre cm","visceralFat:Graisse viscérale"].map(x=>{const [id,l]=x.split(":");return `<label>${l}<input id="${id}" type="number" step="0.1"></label>`}).join("")}</div><button class="primary" id="addMetric">Ajouter pesée</button></article><article class="panel"><h2>Course / marche manuelle</h2><div class="grid four">${["runDistance:Distance km","runDuration:Durée min","runPace:Vitesse moy km/h","runHrAvg:FC moyenne","runHrMax:FC max","runFeeling:Ressenti 1-10","runPain:Douleur 0-5"].map(x=>{const [id,l]=x.split(":");return `<label>${l}<input id="${id}" type="number" step="0.1"></label>`}).join("")}<label>Type<select id="runType"><option value="run">Course</option><option value="walk">Marche</option><option value="bike">Vélo/cardio</option></select></label></div><button class="primary" id="addRun">Ajouter activité</button></article></section>`; }
  function settings(){ const p=profile(); return `<section class="grid"><h1>Réglages</h1><article class="panel"><h2>Profils</h2>${state.profiles.map(x=>`<div class="row"><span>${esc(x.name)}</span><button class="secondary" data-profile="${x.id}">${x.id===state.activeProfileId?"Actif":"Choisir"}</button></div>`).join("")||"<p>Aucun profil.</p>"}${newProfileBox()}</article>${p?profileForm(p):""}<article class="panel"><h2>Médias exercice</h2><p class="muted">${videos.note}</p><label>Base vidéo homogène<input id="videoBase" value="${esc(state.settings.videoBase||videos.defaultBase)}"></label><button class="secondary" id="saveVideoBase">Enregistrer source vidéo</button></article><article class="panel"><h2>Coach vocal</h2><div class="grid three"><label>Activé<select id="ttsEnabled"><option value="true" ${state.settings.tts.enabled?"selected":""}>Oui</option><option value="false" ${!state.settings.tts.enabled?"selected":""}>Non</option></select></label><label>Vitesse<input id="ttsRate" type="number" min="0.7" max="1.4" step="0.1" value="${state.settings.tts.rate}"></label><label>Volume<input id="ttsVolume" type="number" min="0" max="1" step="0.1" value="${state.settings.tts.volume}"></label></div><button class="secondary" id="saveTts">Enregistrer voix</button><button class="secondary" id="testVoice">Tester</button></article><article class="panel"><h2>Worker Garmin optionnel</h2><label>URL Worker<input id="workerUrl" value="${esc(state.settings.workerUrl)}"></label><label>Token app<input id="workerToken" value="${esc(state.settings.workerToken)}" type="password"></label><div class="actions"><button class="secondary" id="saveWorker">Enregistrer</button><button class="secondary" id="testWorker">Tester</button><button class="secondary" id="mockGarmin">Mock Garmin</button></div></article><article class="panel"><h2>Export / import JSON</h2><div class="actions"><button class="primary" id="exportJson">Exporter sans secrets</button><button class="secondary" id="exportJsonSecrets">Exporter avec token Worker</button><label class="secondary file">Importer JSON<input id="importJson" type="file" accept="application/json"></label></div></article><article class="panel"><h2>Maintenance</h2><button class="danger" id="deleteProfile">Supprimer profil actif</button><button class="danger" id="resetAll">Tout effacer localement</button></article></section>`; }
  function newProfileBox(){ return `<div class="newProfile"><div class="grid four"><label>Nom du profil<input id="newProfileName" placeholder="Ex : Damien, Emma..."></label><label>Âge<input id="newAge" type="number"></label><label>Taille cm<input id="newHeight" type="number"></label><label>Poids départ kg<input id="newWeight" type="number" step="0.1"></label><label>Objectif kg<input id="newTarget" type="number" step="0.1"></label></div><button class="primary" id="createProfile">Créer nouveau profil</button></div>`; }
  function profileForm(p){ return `<article class="panel"><h2>Profil actif</h2><div class="grid four"><label>Nom<input id="profileName" value="${esc(p.name)}"></label><label>Âge<input id="age" type="number" value="${p.age||""}"></label><label>Taille cm<input id="heightCm" type="number" value="${p.heightCm||""}"></label><label>Poids départ<input id="startWeightKg" type="number" value="${p.startWeightKg||""}"></label><label>Poids objectif<input id="targetWeightKg" type="number" value="${p.targetWeightKg||""}"></label><label>Jours/semaine<input id="availabilityDays" type="number" value="${p.availabilityDays}"></label></div><label>Matériel<input id="equipment" value="${esc(p.equipment)}"></label><label>Historique sportif<textarea id="sportsHistory">${esc(p.sportsHistory)}</textarea></label><p class="muted">Douleur/fatigue : 0 = aucun problème, 5 = stop/protection.</p><div class="grid four"><label>Dos<input id="backPain" type="number" min="0" max="5" value="${p.health.backPain}"></label><label>Genou<input id="kneePain" type="number" min="0" max="5" value="${p.health.kneePain}"></label><label>Tendon<input id="tendonPain" type="number" min="0" max="5" value="${p.health.tendonPain}"></label><label>Fatigue<input id="fatigue" type="number" min="0" max="5" value="${p.health.fatigue}"></label><label><input id="irradiating" type="checkbox" ${p.health.irradiating?"checked":""}> Douleur irradiée</label><label><input id="neurological" type="checkbox" ${p.health.neurological?"checked":""}> Signe neurologique</label></div><h3>Tests initiaux</h3><div class="grid four">${Object.keys(levels).map(k=>`<label>${k}<select id="level_${k}">${levels[k].map(v=>`<option ${p.levels[k]===v?"selected":""}>${v}</option>`).join("")}</select></label>`).join("")}</div><button class="primary" id="saveProfile">Enregistrer profil + régénérer plan</button></article>`; }
  function needProfile(){ return `<section class="hero"><h1>Profil requis</h1><p>Crée un profil pour activer cette page.</p>${newProfileBox()}</section>`; }
  function media(x){ const src=(state.settings.videoBase||videos.defaultBase)+(x.videoPath||"/"); return `<div class="videoFrame"><iframe src="${esc(src)}" loading="lazy" title="Vidéo ${esc(x.name)}" referrerpolicy="no-referrer" sandbox="allow-scripts allow-same-origin"></iframe></div><details open><summary>Schéma animé offline</summary>${diagram(x)}</details>`; }
  function card(x){ return `<article class="panel exercise"><div class="media">${media(x)}</div><p class="eyebrow">${x.family} · ${x.type} · ${x.sets} série(s)</p><h2>${x.name}</h2><p>${x.short}</p><h3>Comment faire</h3><ol>${x.steps.map(s=>`<li>${esc(s)}</li>`).join("")}</ol><p class="notice">${x.safety}</p></article>`; }
  function diagram(x){ const color={core:"#4f9cff",push:"#f57b45",pull:"#7c6cff",legs:"#5dbb63",mobility:"#b9f66b",cardio:"#ff5c7a",warmup:"#49c6b7",cooldown:"#9aa5a1"}[x.family]||"#4f9cff"; const move=x.family==="legs"?"translate(0 20);translate(0 -8);translate(0 20)":x.family==="push"?"rotate(0 180 120);rotate(-8 180 120);rotate(0 180 120)":x.family==="pull"?"translate(-22 0);translate(20 0);translate(-22 0)":x.family==="cardio"?"translate(-20 0);translate(24 0);translate(-20 0)":"rotate(0 190 115);rotate(8 190 115);rotate(0 190 115)"; return `<svg class="exoSvg" viewBox="0 0 420 220" role="img" aria-label="${esc(x.name)}"><rect width="420" height="220" rx="18" fill="#eef5ef"/><path d="M52 186h316" stroke="#d1dfd5" stroke-width="8" stroke-linecap="round"/><g><animateTransform attributeName="transform" type="${move.includes("rotate")?"rotate":"translate"}" values="${move}" dur="1.4s" repeatCount="indefinite"/><circle cx="150" cy="62" r="18" fill="#12231f"/><path d="M150 82v62M150 105l-58 32M152 106l80 30M150 144l-54 42M154 144l78 40" stroke="#12231f" stroke-width="12" stroke-linecap="round"/></g><path d="M250 52c42 24 66 58 82 112" fill="none" stroke="${color}" stroke-width="10" stroke-linecap="round"/><text x="24" y="34" font-size="18" font-family="Arial" fill="#12231f">${esc(x.name)}</text></svg>`; }
  function chart(rows,a,b){ if(!rows.length) return "<p class='muted'>Aucune donnée.</p>"; const vals=rows.flatMap(r=>[r[a],r[b]]).filter(Boolean), min=Math.min(...vals), max=Math.max(...vals), W=520,H=190, pts=k=>rows.map((r,i)=>`${30+i*(W-60)/Math.max(1,rows.length-1)},${H-24-((r[k]||min)-min)/Math.max(1,max-min)*(H-55)}`).join(" "); return `<svg class="chart" viewBox="0 0 ${W} ${H}"><rect width="${W}" height="${H}" rx="12" fill="#f7faf5"/><polyline points="${pts(a)}" fill="none" stroke="#5dbb63" stroke-width="4"/><polyline points="${pts(b)}" fill="none" stroke="#f57b45" stroke-width="4"/><text x="24" y="24" fill="#62716b">vert poids · orange ventre</text></svg>`; }
  function bar(rows){ if(!rows.length) return "<p class='muted'>Aucune activité.</p>"; const max=Math.max(...rows.map(r=>r.value),1); return `<div class="bars">${rows.map(r=>`<div><span style="height:${Math.max(8,r.value/max*120)}px"></span><small>${esc(r.label)}</small></div>`).join("")}</div>`; }
  function addMetric(){ const p=profile(), w=n("weightKg"); if(!p||!w) return; state.metrics.push({id:uid("metric"),profileId:p.id,source:"manual",measuredAt:new Date().toISOString(),weightKg:w,bodyFatPct:n("bodyFatPct")||null,waterPct:n("waterPct")||null,bmi:n("bmi")||null,boneKg:n("boneKg")||null,muscleKg:n("muscleKg")||null,waistCm:n("waistCm")||null,visceralFat:n("visceralFat")||null}); save("Pesée enregistrée.").then(render); }
  function addRun(){ const p=profile(); if(!p) return; state.activities.push({id:uid("activity"),profileId:p.id,source:"manual",type:el("runType").value,startedAt:new Date().toISOString(),distanceKm:n("runDistance")||null,durationSeconds:n("runDuration")?n("runDuration")*60:null,avgSpeedKmh:n("runPace")||null,hrAvg:n("runHrAvg")||null,hrMax:n("runHrMax")||null,feeling:n("runFeeling")||null,pain:n("runPain")||null}); save("Activité enregistrée.").then(render); }
  function exportJson(secret=false){ const c=clone(state); if(!secret)c.settings.workerToken=""; const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),...c},null,2)],{type:"application/json"})); a.download=`resurgo-export-${TODAY}.json`; a.click(); URL.revokeObjectURL(a.href); }
  async function importJson(file){ const p=JSON.parse(await file.text()); state={...clone(empty),...p,settings:{...empty.settings,...(p.settings||{})},ui:{...empty.ui,...(p.ui||{})}}; delete state.exportedAt; await save("Import JSON terminé."); render(); }
  async function worker(path,init={}){ const base=state.settings.workerUrl.replace(/\/$/,""); if(!base) throw new Error("URL Worker manquante."); const h={"content-type":"application/json",...(init.headers||{})}; if(state.settings.workerToken) h.authorization=`Bearer ${state.settings.workerToken}`; const r=await fetch(base+path,{...init,headers:h}), b=await r.json().catch(()=>({})); if(!r.ok) throw new Error(b.error||`Worker ${r.status}`); return b; }
  async function testWorker(){ try{ const r=await worker("/health"); state.ui.message=`Worker OK: ${r.service||"health"}`; }catch(e){ state.ui.message=`Worker erreur: ${e.message}`; } render(); }
  async function mockGarmin(){ try{ const r=await worker("/v1/garmin/mock-sync",{method:"POST",body:JSON.stringify({profileId:profile()?.id})}); state.metrics.push(...(r.metrics||[])); state.activities.push(...(r.activities||[])); await save("Mock Garmin importé."); }catch(e){ state.ui.message=`Mock Garmin impossible: ${e.message}`; } render(); }
  function render(){ const views={today,plan:planView,session:sessionView,exercises:exercisesView,stats,settings}; $("#app").innerHTML=shell((views[state.ui.view]||today)()); bind(); }
  function on(id,fn){ const x=el(id); if(x) x.onclick=fn; }
  function bind(){
    $$("[data-view]").forEach(b=>b.onclick=()=>{state.ui.view=b.dataset.view; save().then(render);}); $$("[data-start]").forEach(b=>b.onclick=()=>start(b.dataset.start)); $$("[data-profile]").forEach(b=>b.onclick=()=>{state.activeProfileId=b.dataset.profile; save("Profil actif changé.").then(render);});
    on("createProfile",createProfile); on("startToday",()=>start(plan()[0]?.id)); on("shortWeek",()=>{const p=profile(); if(p){makeWeek(p.id,true); save("Semaine courte générée.").then(render);}}); on("activeRest",()=>{const p=profile(); if(p){state.activities.push({id:uid("activity"),profileId:p.id,source:"manual",type:"walk",startedAt:new Date().toISOString(),durationSeconds:1200}); save("Repos actif enregistré.").then(render);}});
    on("saveQuick",()=>{const p=profile(); if(p){p.health.backPain=n("quickBack"); p.health.kneePain=n("quickKnee"); p.health.tendonPain=n("quickKnee"); p.health.fatigue=n("quickFatigue"); save("Check rapide enregistré.").then(render);}}); on("regen",()=>{const p=profile(); if(p){makeWeek(p.id); save("Semaine générée.").then(render);}});
    on("startTimer",startTimer); on("continueAfterRest",continueAfterRest); on("skipRest",continueAfterRest); on("okSet",()=>log("yes",0,"ok")); on("partialSet",()=>log("partial",1,"hard")); on("painSet",()=>log("stop",3,"too_hard")); on("speakCue",()=>{const x=currentEx(); if(x) speak(`${x.name}. ${x.cue}`);}); on("abortSession",()=>{const r=run(); if(r){r.abortedAt=new Date().toISOString(); state.ui.view="today"; stopTimer(); save("Séance arrêtée.").then(render);}});
    on("addMetric",addMetric); on("addRun",addRun); on("saveProfile",()=>{const p=profile(); if(!p)return; p.name=text("profileName")||p.name; p.age=n("age")||p.age; p.heightCm=n("heightCm")||p.heightCm; p.startWeightKg=n("startWeightKg")||p.startWeightKg; p.targetWeightKg=n("targetWeightKg")||p.targetWeightKg; p.availabilityDays=n("availabilityDays")||p.availabilityDays; p.equipment=text("equipment"); p.sportsHistory=text("sportsHistory"); ["backPain","kneePain","tendonPain","fatigue"].forEach(k=>p.health[k]=n(k)); p.health.irradiating=el("irradiating").checked; p.health.neurological=el("neurological").checked; Object.keys(levels).forEach(k=>p.levels[k]=el(`level_${k}`).value); makeWeek(p.id); save("Profil et plan mis à jour.").then(render);});
    on("saveVideoBase",()=>{state.settings.videoBase=text("videoBase")||videos.defaultBase; save("Source vidéo enregistrée.").then(render);}); on("saveTts",()=>{state.settings.tts.enabled=el("ttsEnabled").value==="true"; state.settings.tts.rate=n("ttsRate")||1; state.settings.tts.volume=n("ttsVolume"); save("Voix enregistrée.").then(render);}); on("testVoice",()=>speak("ResurGo est prêt pour la séance.")); on("saveWorker",()=>{state.settings.workerUrl=text("workerUrl"); state.settings.workerToken=el("workerToken").value; save("Worker enregistré.").then(render);}); on("testWorker",testWorker); on("mockGarmin",mockGarmin);
    on("exportJson",()=>exportJson(false)); on("exportJsonSecrets",()=>exportJson(true)); on("deleteProfile",()=>{const p=profile(); if(p&&confirm("Supprimer ce profil local ?")){state.profiles=state.profiles.filter(x=>x.id!==p.id); state.activeProfileId=state.profiles[0]?.id||null; save("Profil supprimé.").then(render);}}); on("resetAll",()=>{if(confirm("Effacer toutes les données locales ResurGo ?")){state=clone(empty); save("Données locales effacées.").then(render);}});
    const imp=el("importJson"); if(imp) imp.onchange=e=>e.target.files[0]&&importJson(e.target.files[0]); const s=el("search"); if(s) s.oninput=e=>{state.ui.search=e.target.value; render();}; const f=el("familyFilter"); if(f) f.onchange=e=>{state.ui.filter=e.target.value; render();};
  }
  async function init(){ state=(await get("app"))||clone(empty); state={...clone(empty),...state,settings:{...empty.settings,...(state.settings||{})},ui:{...empty.ui,...(state.ui||{})}}; if("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(()=>{}); render(); }
  init();
})();
