["Debout, cale l'élastique sous les pieds ou sous un support stable.","Debout, tire les coudes vers le haut sans hausser les épaules.","Debout, garde les poignets sous les coudes.","Contrôle le retour."],"Charge légère et épaules basses.","https://media.musclewiki.com/media/uploads/videos/branded/male-Band-band-upright-row-front.mp4"),
    E("reverse_fly","Oiseau élastique","pull","reps",2,12,50,"Arrière d'épaule et posture.",["Debout, buste légèrement penché, bras presque tendus.","Ouvre doucement les bras.","Serre les omoplates sans cambrer.","Retour lent."],"Charge très légère.","https://media.musclewiki.com/media/uploads/videos/branded/male-band-rear-delt-fly-front.mp4"),
    E("sit_to_stand","Assis-debout chaise haute","legs","reps",3,12,60,"Base jambes avec repère de chaise, hors mode genou fragile.",["Debout devant une chaise haute, pieds largeur bassin.","Debout, recule les hanches vers la chaise.","Effleure la chaise sans t'écraser.","Remonte en poussant le sol."],"Évite cet exercice si l'état genou est à 3/5 ou moins.","https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-bodyweight-box-squat-side.mp4"),
    E("box_squat","Squat sur chaise","legs","reps",3,10,60,"Squat sécurisé avec repère, hors mode genou fragile.",["Debout devant une chaise, recule les hanches.","Touche la chaise sans t'écraser.","Remonte en poussant les pieds.","Garde le buste long."],"Évite cet exercice si l'état genou est à 3/5 ou moins.","https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-bodyweight-box-squat-side.mp4"),
    E("split_squat","Fente statique assistée","legs","reps",2,8,70,"Force unilatérale progressive, hors mode genou fragile.",["Debout en fente, tiens un support.","Descends verticalement avec petite amplitude.","Garde le genou avant aligné.","Remonte sans rebond."],"Évite cet exercice si l'état genou est à 3/5 ou moins.","https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-split-squat-side.mp4"),
    E("glute_bridge","Pont fessier","legs","reps",3,12,45,"Fessiers et protection lombaire.",["Allongé sur le dos, pieds proches des fesses.","Pousse dans les talons.","Monte le bassin sans cambrer.","Redescends lentement."],"Pas de pincement lombaire.","https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-glute-bridge-side.mp4"),
    E("calf_raise","Montées mollets","legs","reps",3,15,45,"Mollets et tendon d'Achille.",["Debout, tiens un mur ou une chaise.","Monte sur pointes.","Marque une pause en haut.","Descends lentement."],"Stop si tendon douloureux.","https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-calf-raises-front.mp4"),
    E("hip_hinge","Charnière hanche","legs","reps",3,10,45,"Apprendre à plier aux hanches sans charger le genou.",["Debout, mains sur hanches.","Envoie les fesses vers l'arrière.","Garde le dos long.","Garde les genoux seulement légèrement fléchis."],"Pas de dos rond sous fatigue.","/"),
    E("quad_set","Contraction quadriceps genou","knee_rehab","time",3,20,25,"Activation douce du quadriceps pour soutenir la rotule.",["Allongé sur le dos ou assis jambes tendues, place une serviette sous le genou.","Écrase doucement la serviette avec l'arrière du genou.","Tiens la contraction sans bloquer la respiration.","Relâche lentement."],"Douleur maximale 2/5, sinon stop et avis kiné.","/"),
    E("straight_leg_raise","Lever de jambe tendue","knee_rehab","reps",2,10,45,"Renforcement quadriceps sans flexion profonde du genou.",["Allongé sur le dos, jambe gauche pliée et jambe droite tendue.","Contracte la cuisse droite en gardant le genou droit tendu.","Lève la jambe droite tendue jusqu'à l'alignement de la cuisse gauche.","Redescends la jambe droite lentement sans la laisser tomber.","À la deuxième série, change de jambe pour faire le même travail de l'autre côté."],"Stop si douleur genou, hanche ou dos.","/","https://www.verywellhealth.com/how-to-the-straight-leg-raise-2696526"),
    E("seated_knee_extension","Extension de genou assise limitée","knee_rehab","reps",2,10,45,"Quadriceps assis, amplitude courte et contrôlée.",["Assis sur une chaise, dos droit et pieds au sol.","Tends une jambe seulement jusqu'à une amplitude confortable.","Marque une pause courte sans verrouiller fort le genou.","Redescends lentement.","À la deuxième série, change de jambe pour rester équilibré entre les deux côtés."],"Reste en petite amplitude si la rotule tire.","/","https://www.verywellhealth.com/exercises-for-arthritic-knees-8648827"),
    E("standing_hamstring_curl","Flexion ischio debout","knee_rehab","reps",2,10,40,"Renforcement arrière de cuisse pour stabiliser le genou.",["Debout derrière une chaise, mains sur le dossier.","Plie un genou pour ramener le talon vers la fesse.","Garde les cuisses alignées et le bassin fixe.","Redescends lentement.","À la deuxième série, change de jambe pour rester équilibré entre les deux côtés."],"Amplitude douce, pas de crampe ni douleur vive.","/","https://www.verywellhealth.com/exercises-for-arthritic-knees-8648827"),
    E("clamshell","Coquillage côté","knee_rehab","reps",2,12,35,"Hanche et contrôle de l'alignement genou-rotule.",["Allongé sur le côté, genoux pliés et pieds ensemble.","Garde le bassin stable.","Ouvre le genou du dessus sans rouler en arrière.","Referme lentement.","À la deuxième série, change de côté pour rester équilibré entre les deux hanches."],"Le mouvement doit rester dans la hanche, pas dans le bas du dos.","/","https://www.verywellhealth.com/medial-knee-pain-exercises-5120563"),
    E("hip_abduction_side","Lever de jambe côté","knee_rehab","reps",2,10,40,"Moyen fessier pour mieux tenir l'axe du genou.",["Allongé sur le côté, jambe du dessous pliée et jambe du dessus tendue.","Garde les orteils légèrement vers l'avant.","Lève la jambe du dessus sans tourner le bassin.","Redescends lentement.","À la deuxième série, change de côté pour rester équilibré entre les deux hanches."],"Stop si douleur hanche ou lombaire.","/","https://www.verywellhealth.com/exercises-for-arthritic-knees-8648827"),
    E("hip_flexor","Mobilité psoas","mobility","time",2,35,20,"Ouverture de hanche.",["Au sol en fente basse, pose le genou arrière sur un coussin.","Rentre légèrement le bassin.","Respire lentement.","Change de côté."],"Ne force jamais, évite si le genou au sol est douloureux.","/bodyweight/male/stretching/hip-flexor-stretch"),
    E("thoracic_rotation","Rotation thoracique","mobility","reps",2,8,20,"Mobilité haut du dos.",["À quatre pattes, mains sous épaules.","Place une main derrière la tête.","Tourne le haut du dos sans bouger le bassin.","Regarde le coude."],"Pas de douleur vive.","https://media.musclewiki.com/media/uploads/videos/branded/male-Bodyweight-bodyweight-thoracic-spine-rotation-side.mp4"),
    E("ankle_wall","Étirement mollet au mur","mobility","time",2,35,20,"Étirement du mollet contre le mur.",["Debout face au mur, place les mains au mur.","Recule une jambe en gardant le talon au sol.","Avance doucement le bassin.","Change de côté."],"Tension douce, pas de douleur tendon.","https://media.musclewiki.com/media/uploads/videos/branded/male-Recovery-gastrocnemius-stretch-unilateral-on-wall-front.mp4"),
    E("hamstring_floss","Floss ischios","mobility","reps",2,10,20,"Souplesse arrière de jambe.",["Allongé sur le dos ou assis, allonge la jambe sans verrouiller.","Pointe puis fléchis le pied.","Garde une amplitude confortable.","Respire."],"Pas de tiraillement nerveux fort.","/"),
    E("shoulder_wall_slide","Étirement flexion épaule au mur","mobility","time",2,35,30,"Mobilité douce de l'épaule contre un mur.",["Debout face au mur, place une main ou les avant-bras au mur.","Avance doucement le buste pour ouvrir l'épaule.","Garde les côtes basses.","Respire sans forcer."],"Stop si pincement épaule.","https://media.musclewiki.com/media/uploads/videos/branded/male-Recovery-shoulder-flexion-stretch-wall-standing-side.mp4"),
    E("brisk_walk","Marche active","cardio","time",1,1800,0,"Cardio bas impact.",["Debout, pars sur terrain plat.","Garde un rythme où tu peux parler.","Utilise les bras sans te crisper.","Ralentis si douleur."],"Terrain plat si genou fragile, pas de côte forcée.","/"),
    E("easy_run","Course facile","cardio","time",1,1800,0,"Footing très facile autorisé en mode genou fragile si tout reste indolore.",["Debout, démarre très lentement sur terrain plat.","Garde une aisance où tu peux parler sans effort.","Reste en foulée courte et sans côte.","Stop si tendon, genou ou douleur irradiée."],"Genou fragile: plat, facile, sans fractionné, 45 min maximum.","/"),
    E("run_walk","Alternance course-marche","cardio","time",1,1500,0,"Marche-course progressive autorisée en mode genou fragile.",["Debout sur terrain plat, alterne 1-3 min course facile et marche.","Reste en aisance totale.","Note douleur et souffle.","Augmente seulement si tout va bien le lendemain."],"Genou fragile: plat, facile, sans côte, 45 min maximum.","/"),
    E("low_impact_cardio","Cardio bas impact","cardio","time",1,1500,0,"Vélo doux ou marche plate, sans impact.",["Assis sur vélo ou debout en marche plate, reste en zone facile.","Garde une cadence régulière.","Contrôle la respiration.","Finis avec la sensation de pouvoir continuer."],"Pas de côte, pas de step et pas de résistance lourde si genou fragile.","/"),
    E("step_up_low","Step-up bas","legs","reps",2,10,60,"Montée sur marche basse, hors mode genou fragile.",["Debout devant une marche basse et stable.","Monte en poussant dans le talon.","Redescends lentement.","Change de jambe."],"Évite cet exercice si l'état genou est à 3/5 ou moins.","https://media.musclewiki.com/media/uploads/videos/branded/male-Recovery-step-up-knee-drive-side.mp4"),
    E("cooldown_breathing","Retour au calme respiration","cooldown","time",1,180,0,"Retour au calme.",["Assis ou allongé, allonge l'expiration.","Relâche les épaules.","Observe douleur et fatigue.","Note le ressenti."],"Reste confortable.","/")
  ];
  const empty = {
    schemaVersion:"1.1.0-vanilla", activeProfileId:null, profiles:[], assessments:[], plans:[], sessionRuns:[], metrics:[], activities:[], exerciseVideos:{}, exerciseMetaOverrides:{},
    sources:[{id:"manual",label:"Manuel",enabled:true,priority:3},{id:"json_import",label:"Import JSON",enabled:true,priority:2},{id:"mock_garmin",label:"Mock Garmin",enabled:true,priority:1},{id:"worker",label:"Worker Cloudflare",enabled:false,priority:1}],
    settings:{ theme:"auto", hideInstallPrompt:false, notifications:{enabled:true,reminderTime:"08:00",lastNotifiedDate:"",askedOnInstall:false}, tts:{enabled:true,rate:1,pitch:1,volume:1,countdown:true,rest:true,cues:true,safetyAlways:true}, workerUrl:"", workerToken:"", videoBase:videos.defaultBase },
    ui:{ view:"today", search:"", searchDraft:"", filter:"all", message:"", modal:null }
  };
  let state = clone(empty), tick = null, left = 0, voiceSeq = 0, deferredInstallPrompt = null, swRegistration = null, updateWaiting = null, remoteVersion = APP_VERSION, remoteBuild = APP_BUILD, messageTimer = null, smileyDismissBound = false, reminderTimer = null;
  let bodyMapSvg = { male:"", female:"" };

  function exerciseMeta(id,family,type,sets,amount){
    const durationMin=type==="time"?Math.round((amount||0)/60):0;
    const rehab=family==="knee_rehab", mobility=family==="mobility"||family==="cooldown"||family==="warmup", cardio=family==="cardio";
    const heavyIds=["box_squat","split_squat","step_up_low"], lightIds=["quad_set","clamshell","hip_flexor","ankle_wall","hamstring_floss","cooldown_breathing","warmup_flow","brisk_walk","run_walk"];
    let load="moderate";
    if(mobility||rehab||lightIds.includes(id)) load="light";
    else if(heavyIds.includes(id)) load="hard";
    else if(cardio&&durationMin>=30) load="moderate";
    return {
      load,
      role:mobility?"mobility":rehab?"rehab":cardio?"cardio":"strength",
      compatibleAddon:mobility||rehab||lightIds.includes(id),
      recoveryCost:load==="hard"?2:load==="moderate"?1:0
    };
  }
  const trainingLoadOptions = ["light","moderate","hard"];
  const trainingRoleOptions = ["mobility","rehab","cardio","strength"];
  const trainingLabels = {
    load:{light:"Léger",moderate:"Normal",hard:"Dur"},
    role:{mobility:"Mobilité / étirement",rehab:"Rééducation / kiné",cardio:"Cardio",strength:"Renforcement"}
  };
  function effectiveTraining(x){
    const override=state.exerciseMetaOverrides?.[x.id]||{};
    return {...x.training,...override};
  }
  function E(id,name,family,type,sets,amount,rest,short,steps,safety,path,sourceUrl="") {
    return { id,name,family,type,sets,rest,short,steps,safety,cue:steps[0], reps:type==="reps"?amount:null, seconds:type==="time"?amount:null, videoPath:path, sourceUrl, training:exerciseMeta(id,family,type,sets,amount) };
  }
  function db(){ return new Promise((ok,ko)=>{ const r=indexedDB.open(DB,1); r.onupgradeneeded=()=>r.result.createObjectStore(STORE); r.onsuccess=()=>ok(r.result); r.onerror=()=>ko(r.error); }); }
  async function get(k)
