  // Regrouper ici les helpers de visualisation, d'import/export,
  // de communication Worker et de cycle de vie PWA.
pull:["Posture haute","Tire les coudes vers l'arrière", {head:[172,74],neck:[172,96],mid:[172,136],hip:[172,170],lhand:[252,120],rhand:[252,120],lknee:[150,206],lfoot:[130,222],rknee:[194,206],rfoot:[218,222]}, {head:[172,74],neck:[172,96],mid:[172,136],hip:[172,170],lhand:[204,126],rhand:[210,126],lknee:[150,206],lfoot:[130,222],rknee:[194,206],rfoot:[218,222]}], cardio:["Foulée courte","Reste facile et régulier", {head:[142,76],neck:[142,98],mid:[132,136],hip:[122,166],lhand:[96,126],rhand:[178,124],lknee:[100,194],lfoot:[68,218],rknee:[154,190],rfoot:[202,206]}, {head:[260,76],neck:[260,98],mid:[250,136],hip:[240,166],lhand:[296,126],rhand:[218,124],lknee:[268,190],lfoot:[318,206],rknee:[218,194],rfoot:[184,218]}], mobility:["Amplitude douce","Bouge lentement sans forcer", {head:[166,66],neck:[166,88],mid:[166,130],hip:[166,168],lhand:[118,112],rhand:[214,112],lknee:[144,204],lfoot:[122,222],rknee:[188,204],rfoot:[214,222]}, {head:[250,66],neck:[250,88],mid:[238,130],hip:[226,168],lhand:[170,104],rhand:[318,82],lknee:[204,204],lfoot:[178,222],rknee:[250,204],rfoot:[278,222]}]}; if(map[x.id]) return map[x.id]; if(["front_plank","side_plank_knees"].includes(x.id)) return map.plank; if(x.family==="push") return map.push; if(x.family==="pull") return map.pull; if(["glute_bridge"].includes(x.id)) return map.bridge; if(x.family==="legs") return map.squat; if(x.family==="cardio") return map.cardio; if(x.family==="knee_rehab") return map.mobility; if(x.family==="mobility"||x.family==="warmup"||x.family==="cooldown") return map.mobility; return map.mobility; }
  function legacyPoseDiagram(x){ const [a,b,start,end]=poseTemplate(x), c={core:"#4f9cff",push:"#f57b45",pull:"#7c6cff",legs:"#5dbb63",knee_rehab:"#19a974",mobility:"#b9f66b",cardio:"#ff5c7a",warmup:"#49c6b7",cooldown:"#9aa5a1"}[x.family]||"#4f9cff"; return `<svg class="exoSvg poseSvg" viewBox="0 0 420 250" role="img" aria-label="${esc(x.name)}"><rect width="420" height="250" rx="20" fill="#eef5ef"/><text x="22" y="31" font-size="18" font-family="Arial" font-weight="800" fill="#12231f">${esc(x.name)}</text><path d="M42 222h336" stroke="#d1dfd5" stroke-width="8" stroke-linecap="round"/><g class="poseStart">${poseLine(start,"",.22)}</g><g class="poseMove">${poseLine(end)}</g><path d="M112 52 C170 28 247 28 306 52" fill="none" stroke="${c}" stroke-width="8" stroke-linecap="round"/><path d="M296 42 l22 11 l-22 11" fill="none" stroke="${c}" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><text x="34" y="236" fill="#62716b" font-size="13">${esc(a)}</text><text x="212" y="236" fill="#62716b" font-size="13">${esc(b)}</text></svg>`; }
  function bodyPartIds(x){ const byId={quad_set:["quads","knees"],straight_leg_raise:["quads","hips","knees"],seated_knee_extension:["quads","knees"],standing_hamstring_curl:["hamstrings","hips","knees"],clamshell:["glutes","hips","knees"],hip_abduction_side:["glutes","hips","knees"]}; if(byId[x.id]) return byId[x.id]; const t=targets(x).join(" ").toLowerCase(), has=s=>t.includes(s), ids=new Set(); if(has("abdos")||has("oblique")||has("respiration")) ["abdominals","obliques"].forEach(i=>ids.add(i)); if(has("pectoraux")) ids.add("chest"); if(has("épaule")||has("arrière épaules")) ["front-shoulders","rear-shoulders","shoulders","traps"].forEach(i=>ids.add(i)); if(has("dos")||has("dorsal")||has("haut du dos")) ["lats","traps","traps-middle","lowerback","rear-shoulders"].forEach(i=>ids.add(i)); if(has("lombaire")) ["lowerback","lats"].forEach(i=>ids.add(i)); if(has("fessier")||has("hanche")||has("psoas")||has("stabilisateurs de hanche")||has("articulation de hanche")) ["hips","glutes"].forEach(i=>ids.add(i)); if(has("cuisse")||has("ischios")||has("jambes")||has("quadriceps")) ["quads","hamstrings"].forEach(i=>ids.add(i)); if(has("genou")||has("rotule")) ids.add("knees"); if(has("mollet")||has("cheville")) ["calves","ankles"].forEach(i=>ids.add(i)); if(has("bras")||has("biceps")) ids.add("biceps"); if(has("triceps")) ids.add("triceps"); if(has("cardio")||has("coeur")) ["quads","calves","hamstrings"].forEach(i=>ids.add(i)); return [...ids]; }
  function injectedBodyMap(kind, ids, label){ let svg=bodyMapSvg[kind]||""; if(!svg) return `<img class="anatomyMap detailedBodyMap anatomyModel" src="${bodyMapAssets[kind]}" alt="${esc(label)}">`; svg=svg.replace(/<svg\b([^>]*)>/,(m,attrs)=>{ const cleaned=attrs.replace(/\sclass="[^"]*"/,"").replace(/\srole="[^"]*"/,"").replace(/\saria-label="[^"]*"/,""); return `<svg${cleaned} class="anatomyMap detailedBodyMap anatomyModel" role="img" aria-label="${esc(label)}">`; }); ids.forEach(id=>{ svg=svg.replace(new RegExp(`(<[^>]*\\bid="${id}"[^>]*\\bclass=")([^"]*)(")`,`g`),`$1hot $2$3`); svg=svg.replace(new RegExp(`(<[^>]*\\bclass=")([^"]*)("[^>]*\\bid="${id}"[^>]*>)`,`g`),`$1hot $2$3`); }); return svg; }
  function muscleMap(x){ const kind=profile()?.gender==="female"?"female":"male"; return injectedBodyMap(kind,bodyPartIds(x),`Zones travaillées ${x.name}`); }
  function chart(rows,a,b,target=null,large=false){ if(!rows.length) return "<p class='muted'>Aucune donnée.</p>"; const vals=rows.flatMap(r=>b?[Number(r[a]),Number(r[b])]:[Number(r[a])]).filter(Number.isFinite); if(target!=null) vals.push(Number(target)); if(!vals.length) return "<p class='muted'>Aucune donnée.</p>"; const min=Math.min(...vals), max=Math.max(...vals), W=large?820:520,H=large?310:190, x=i=>30+i*(W-60)/Math.max(1,rows.length-1), y=v=>H-24-((v-min)/Math.max(1,max-min)*(H-55)), pts=k=>rows.map((r,i)=>`${x(i)},${y(Number(r[k])||min)}`).join(" "), targetY=target!=null?y(Number(target)):null, legend=b?"bleu poids · vert cible · orange ventre":(a==="waistCm"?"tour de ventre":"bleu poids · vert cible"); return `<svg class="chart ${large?"chartLarge":""}" viewBox="0 0 ${W} ${H}"><rect width="${W}" height="${H}" rx="12" fill="var(--chart-bg)"/>${targetY?`<line x1="30" y1="${targetY}" x2="${W-30}" y2="${targetY}" stroke="var(--green)" stroke-width="3" stroke-dasharray="8 8"/><text x="${W-150}" y="${targetY-8}" fill="var(--green)">cible ${target} kg</text>`:""}<polyline points="${pts(a)}" fill="none" stroke="var(--blue)" stroke-width="4"/>${b?`<polyline points="${pts(b)}" fill="none" stroke="var(--orange)" stroke-width="4"/>`:""}<text x="24" y="24" fill="var(--muted)">${legend}</text></svg>`; }
  function bar(rows){ if(!rows.length) return "<p class='muted'>Aucune activité.</p>"; const max=Math.max(...rows.map(r=>r.value),1); return `<div class="bars">${rows.map(r=>`<div><span style="height:${Math.max(8,r.value/max*120)}px"></span><small>${esc(r.label)}</small></div>`).join("")}</div>`; }
  function dateInputIso(id){ const raw=(el(id)?.value||TODAY).slice(0,10); return `${raw}T12:00:00.000Z`; }
  function addMetric(){ const p=profile(), w=num("weightKg"); if(!p||!w) return; state.metrics.push({id:uid("metric"),profileId:p.id,source:"manual",measuredAt:dateInputIso("metricDate"),weightKg:w,bodyFatPct:num("bodyFatPct"),waterPct:num("waterPct"),bmi:num("bmi"),boneKg:num("boneKg"),muscleKg:num("muscleKg"),waistCm:num("waistCm")}); state.ui.modal=null; save("Pesée enregistrée.").then(render); }
  function addRun(){ const p=profile(); if(!p) return; state.activities.push({id:uid("activity"),profileId:p.id,source:"manual",type:el("runType").value,startedAt:dateInputIso("runDate"),distanceKm:num("runDistance"),durationSeconds:num("runDuration")?num("runDuration")*60:null,avgSpeedKmh:num("runPace"),hrAvg:num("runHrAvg"),hrMax:num("runHrMax"),feeling:num("runFeeling"),pain:num("runPain")}); refreshPlanAfterActivity(p.id); state.ui.modal=null; save("Activité enregistrée et plan recalculé.").then(render); }
  function exportJson(secret=false){ const c=clone(state); if(!secret)c.settings.workerToken=""; const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),...c},null,2)],{type:"application/json"})); a.download=`resurgo-export-${TODAY}.json`; a.click(); URL.revokeObjectURL(a.href); }
  async function importJson(file){ const p=JSON.parse(await file.text()); state={...clone(empty),...p,settings:{...empty.settings,...(p.settings||{})},ui:{...empty.ui,...(p.ui||{})}}; delete state.exportedAt; state.profiles.forEach(x=>refreshPlanAfterActivity(x.id)); await save("Import JSON terminé et plan recalculé."); render(); }
  async function worker(path,init={}){ const base=state.settings.workerUrl.replace(/\/$/,""); if(!base) throw new Error("URL Worker manquante."); const h={"content-type":"application/json",...(init.headers||{})}; if(state.settings.workerToken) h.authorization=`Bearer ${state.settings.workerToken}`; const r=await fetch(base+path,{...init,headers:h}), b=await r.json().catch(()=>({})); if(!r.ok) throw new Error(b.error||`Worker ${r.status}`); return b; }
  async function testWorker(){ try{ const r=await worker("/health"); state.ui.message=`Worker OK: ${r.service||"health"}`; }catch(e){ state.ui.message=`Worker erreur: ${e.message}`; } render(); }
  async function mockGarmin(){ try{ const p=profile(); const r=await worker("/v1/garmin/mock-sync",{method:"POST",body:JSON.stringify({profileId:p?.id})}); state.metrics.push(...(r.metrics||[])); state.activities.push(...(r.activities||[])); if(p) refreshPlanAfterActivity(p.id); await save("Mock Garmin importé et plan recalculé."); }catch(e){ state.ui.message=`Mock Garmin impossible: ${e.message}`; } render(); }
  async function installPwa(){ if(!deferredInstallPrompt) return; deferredInstallPrompt.prompt(); await deferredInstallPrompt.userChoice.catch(()=>{}); deferredInstallPrompt=null; state.settings.hideInstallPrompt=true; save().then(render); }
  function applyHotUpdate(){ if(updateWaiting){ updateWaiting.postMessage({type:"SKIP_WAITING"}); return; } if(swRegistration?.waiting){ swRegistration.waiting.postMessage({type:"SKIP_WAITING"}); return; } if(swRegistration) swRegistration.update(); }
  async function checkOnlineVersion(){
    if(!navigator.onLine) return;
    try{
      const r=await fetch(`./version.json?ts=${Date.now()}`,{cache:"no-store"});
      const v=await r.json();
      remoteVersion=v.version||APP_VERSION;
      remoteBuild=v.buildId||remoteVersion;
      if(remoteBuild!==APP_BUILD||remoteVersion!==APP_VERSION) state.ui.message=`Nouvelle version ${remoteVersion} détectée. Mise à jour en cours.`;
      if(swRegistration) await swRegistration.update();
