;} stopTimer(); left=x.seconds; updateTimer(); speak("Timer lancé."); tick=setInterval(()=>{ left--; if(state.settings.tts.countdown&&[10,5,3,2,1].includes(left)) speak(String(left),"timer"); updateTimer(); if(left<=0){stopTimer(); speak("Temps terminé. Enregistre le résultat.");}},1000); }
  function startRest(seconds){ stopTimer(); left=seconds; if(state.settings.tts.rest) speak(`Repos ${seconds} secondes. La prochaine série ne démarre pas automatiquement.`,"timer"); tick=setInterval(()=>{ left--; if(state.settings.tts.countdown&&[30,20,10,5,3,2,1].includes(left)) speak(left===30||left===20||left===10?`${left} secondes` : String(left),"timer"); updateTimer(); if(left<=0){stopTimer(); speak("Repos terminé. Appuie sur commencer quand tu es prêt.","timer"); render();}},1000); }
  function continueAfterRest(){ const r=run(); if(!r?.restNext) return; r.exerciseIndex=r.restNext.exerciseIndex; r.setIndex=r.restNext.setIndex; r.mode="work"; r.restNext=null; left=0; speakExerciseGuide(currentEx(),"Prêt."); save("Série suivante prête.").then(render); }
  function stopTimer(){ if(tick) clearInterval(tick); tick=null; }
  function updateTimer(){ const t=el("timer"); if(t) t.textContent=sec(Math.max(left,0)); }
  function applyTheme(){ document.documentElement.dataset.theme=state.settings.theme||"auto"; }
  function isStandalone(){ return window.matchMedia("(display-mode: standalone)").matches || navigator.standalone; }
  function pwaPrompt(){
    if(isStandalone()) return "";
    const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);
    if(deferredInstallPrompt) return `<div class="pwaPrompt"><div><strong>Installer ResurGo Fitness</strong><span>Ajoute l'app à l'écran d'accueil pour un usage plein écran et offline.</span></div><button class="primary" id="installPwa">Installer</button><button class="secondary" id="dismissPwa">Plus tard</button></div>`;
    if(ios) return `<div class="pwaPrompt"><div><strong>Installer ResurGo Fitness</strong><span>Sur iPhone/iPad : Partager, puis “Sur l'écran d'accueil”.</span></div><button class="secondary" id="dismissPwa">OK</button></div>`;
    return "";
  }
  function updatePrompt(){ return remoteVersion!==APP_VERSION||updateWaiting ? `<div class="pwaPrompt update"><div><strong>Mise à jour ${esc(remoteVersion)} détectée</strong><span>Installation automatique en cours. Les données locales sont conservées.</span></div></div>` : ""; }
  function healthScore(v){ return v == null || v === "" ? null : Math.max(0,Math.min(5,5-Number(v))); }
  function scoreToLoad(v){ return v == null || v === "" || Number.isNaN(Number(v)) ? null : Math.max(0,Math.min(5,5-Number(v))); }
  function bodyStateItems(kind,p){
    const kneeScore=healthScore(p.health.kneePain == null && p.health.tendonPain == null ? null : Math.max(p.health.kneePain ?? 0,p.health.tendonPain ?? 0));
    return kind==="quick"
      ? [{id:"quickBack",label:"Dos",score:healthScore(p.health.backPain)},{id:"quickKnee",label:"Genoux / Tendons",score:kneeScore},{id:"quickFatigue",label:"Énergie / Fatigue",score:healthScore(p.health.fatigue)}]
      : [{id:"profileBack",label:"Dos",score:healthScore(p.health.backPain)},{id:"profileKnee",label:"Genoux / Tendons",score:kneeScore},{id:"profileFatigue",label:"Énergie / Fatigue",score:healthScore(p.health.fatigue)}];
  }
  function bodyStateControls(kind,p,extraClass="quickSmiley"){ return `<div class="smileyGrid ${extraClass}">${bodyStateItems(kind,p).map(x=>ratingControl(x.id,x.label,x.score)).join("")}</div>`; }
  function ratingControl(id,label,score){
    const blank=score == null || score === "", safe=blank ? "" : Math.max(0,Math.min(5,Number(score))), m=blank ? {face:"◯",label:"Non renseigné",tone:"empty"} : (mood[safe]||mood[0]);
    return `<div class="smileyField ${m.tone}" data-smiley="${id}"><span>${esc(label)}</span><input type="hidden" id="${id}" value="${blank?"":safe}"><details><summary><b>${m.face}</b><small>${blank?"--/5":`${safe}/5`}</small></summary><div class="smileyChoices">${mood.map((x,i)=>`<button type="button" class="${x.tone} ${i===safe?"selected":""}" data-rate-target="${id}" data-rate-value="${i}" title="${i}/5 - ${esc(x.label)}"><b>${x.face}</b><span>${i}/5</span></button>`).join("")}</div></details></div>`;
  }
  function levelOptions(k,value){ return levels[k].map(v=>`<option value="${v}" ${value===v?"selected":""}>${v} - ${esc(levelText[k][v])}</option>`).join(""); }
  function levelHelp(){ return `<details class="levelHelp"><summary>Comment choisir les tests initiaux ?</summary><div class="helpGrid">${Object.keys(levelNames).map(k=>`<div><strong>${levelNames[k]}</strong><p>${levels[k].map(v=>`${v}: ${levelText[k][v]}`).join(" · ")}</p></div>`).join("")}</div></details>`; }

  function shell(content){ const nav=["today","plan","session","exercises","stats","settings"]; const names={today:"Aujourd'hui",plan:"Plan",session:"Séance",exercises:"Exos",stats:"Stats",settings:"Réglages"}, icons={today:"⌂",plan:"▦",session:"▶",exercises:"◉",stats:"◷",settings:"⚙"}, notice=[updatePrompt(),state.settings.hideInstallPrompt?pwaPrompt().replace("pwaPrompt","pwaPrompt hidden"):pwaPrompt(),state.ui.message?`<p class="notice toastNotice">${esc(state.ui.message)}</p>`:""].join(""); return `<main class="app"><div class="fixedShell"><header class="top"><div class="brand"><img class="logo" src="./icon.svg" alt="ResurGo Fitness"><span>ResurGo Fitness</span></div><span class="pill">${navigator.onLine?"Online":"Offline"} · v${APP_VERSION}</span></header></div><nav class="tabs">${nav.map(v=>`<button class="tab ${state.ui.view===v?"active":""}" data-view="${v}"><span>${icons[v]}</span><span>${names[v]}</span></button>`).join("")}</nav><div class="toastLayer">${notice}</div><section class="content">${content}</section>${modalLayer()}</main>`; }
  function today(){ const p=profile(); if(!p) return `<section class="hero"><p class="eyebrow">Coach sportif local-first</p><h1>ResurGo Fitness</h1><p>PWA offline avec séances guidées, exercices détaillés, stats, saisie course/balance et Worker Garmin optionnel.</p>${newProfileBox()}</section>`; const d=decision(p), m=latestMetric(), g=goalInfo(p), pick=coachPickToday(p), s=pick.session, next=nextPlannedSession(), done=!plan().length&&weekPlan().length; return `<section class="grid"><h1>Aujourd'hui</h1><div class="grid two todayMain"><article class="panel"><p class="eyebrow">Profil actif</p><h2>${esc(p.name)}</h2><div class="row"><span>Objectif</span><strong>${p.startWeightKg||"?"} → ${p.targetWeightKg||"?"} kg</strong></div><div class="row"><span>Cadence cible</span><strong>${esc(g.text)}</strong></div><div class="row"><span>Poids récent</span><strong>${m?m.weightKg+" kg":"À saisir"}</strong></div><div class="row coachOrientation"><span>Orientation du coach</span><strong class="status ${d[0]}">${d[1]}</strong></div><p class="muted">${d[2]}</p><div class="actions compactActions twoButtons"><button class="secondary" id="openMetricModal">Ajouter pesée</button><button class="secondary" id="openActivityModal">Ajouter activité</button></div></article><article class="panel quickPanel"><h2>Check rapide</h2><p class="muted">5 = tout va bien, 0 = alerte rouge.</p>${bodyStateControls("quick",p,"quickSmiley")}</article><article class="panel todaySession ${s?"":"restDay"}"><p class="eyebrow">${esc(pick.title)}</p><h2>${s?esc(s.title):"Repos"}</h2><p class="muted">${s?`${dayLabel(s.date||TODAY)} · ${typeLabel(s.type)} · ${s.minutes} min · ${s.exerciseIds.length} blocs`:(next?`Prochaine séance : ${dayLabel(next.date||TODAY)} · ${next.title}`:"Aucune séance active.")}</p><p class="muted">${esc(pick.reason)}</p><div class="actions">${s?`<button class="primary" id="startToday">Démarrer</button>`:""}${done?`<button class="primary" id="nextWeek">Semaine suivante</button>`:""}<button class="secondary" id="goPlan">Voir la semaine</button><button class="secondary" id="activeRest">Repos actif</button></div></article></div><p class="notice">Sécurité : stop en cas de douleur irradiée, faiblesse, engourdissement, douleur forte ou symptôme inquiétant.</p></section>`; }
  function planView(){ if(!profile()) return needProfile(); const p=profile(), items=weekPlan(), short=!!items[0]?.short, agenda=weekAgenda(p), pick=coachPickToday(p), done=!plan().length&&items.length; return `<section class="grid"><h1>Plan adaptatif</h1><div class="switchRow"><button class="${short?"secondary":"primary"} ${short?"":"isActive"}" id="regenNormal">Semaine normale</button><button class="${short?"primary isActive":"secondary"}" id="regenShort">Semaine minimale viable</button></div><article class="panel planSummary"><h2>Semaine ${items[0]?.week||1}</h2><div class="chips">${frequencySummary(p).map(x=>`<span>${esc(x)}</span>`).join("")}</div>${pick.session?`<p class="muted">Aujourd'hui le coach conseille : ${esc(pick.session.title)}. ${esc(pick.reason)}</p>`:`<p class="muted">Aujourd'hui le coach conseille : repos. ${esc(pick.reason)}</p>`}${done?`<button class="primary" id="nextWeek">Générer semaine suivante</button>`:""}</article><div class="weekAgenda">${agenda.map(d=>d.session?`<article class="panel dayCard ${d.session.completedAt?"doneDay":""}"><p class="eyebrow">${dayLabel(d.date)} · ${typeLabel(d.session.type)}${d.session.completedAt?" · fait":""}</p><h2>${esc(d.session.title)}</h2><p class="muted">${d.session.minutes} min · ${d.session.exerciseIds.length} blocs</p><div class="chips">${d.session.exerciseIds.map(id=>`<span>${exercise(id).name}</span>`).join("")}</div>${d.session.completedAt?`<span class="status green">Terminé</span>`:`<button class="primary" data-start="${d.session.id}">Lancer</button>`}</article>`:`<article class="panel dayCard restDay"><p class="eyebrow">${dayLabel(d.date)}</p><h2>Repos</h2><p class="muted">Récupération, marche douce possible si tu veux bouger.</p></article>`).join("")}</div></section>`; }
